### ISSUE TITLE
Understanding part number

### ISSUE THREAD

**Issue by Matheus-Garbelini** [christian-kramer/JieLi-AC690X-Familiarization#2]
Hi @christian-kramer thanks a lot for your findings.
I've got one with part number AC20BP08128-25c4

Do you know for what official part number this would translate to? I'm assuming this is some variant of AC690X or AC691X?

There is a website that lists all their BT socs, but this strange part number does not match any:
http://www.chenbingdom.com/en/product.asp?classid=52&pages=1

**Comment by Bogdancev** [comment]
It is some other number rather than part number.
25C4 might mean AC692x series, but I cannot be 100% sure on that.

Assuming you have SOP-24 package:
Can you see to which pin FM antenna is connected? On AC692x it's placed next to Bluetooth antenna pin. On AC690x it's on the opposite side.

There is also a difference in USB pins, on AC692x they are 4 and 5, on AC690x they are 3 and 4. Easily checked by multimeter.

Then if you use the method described here to trigger "Device Firmware Update" mode, you will see it as BR17 for AC690x and BR21 for AC692x.

**Comment by Matheus-Garbelini** [comment]
@Bogdancev thanks for your reply, just a second. I will take a picture

**Comment by Matheus-Garbelini** [comment]
@Bogdancev I'll try your advice and check the pins against the official datasheets then. I can confirm that this is 100% BT version 5.0 because I can check the actual LMP Bluetooth packet version response coming from this chip.

![2021-4-19 19-48-23](https://user-images.githubusercontent.com/6465668/115236955-8f61bb80-a14e-11eb-9c56-5490e15af78e.jpg)


![Screenshot_20210419_203533](https://user-images.githubusercontent.com/6465668/115237165-cfc13980-a14e-11eb-9a6e-1379c047ca6c.png)

**Comment by Bogdancev** [comment]
OK, USB pins match AC692x. Bluetooth 5 is only available in AC692x, AC690x has 4.1.
So here we go, you are in troubles.

**Comment by Matheus-Garbelini** [comment]
Thanks, checking again the schematics, this chip matches exactly to **[AC6925C](http://www.chenbingdom.com/uploadfile/201863011283697416.pdf)** as you hinted then!
This is actually awesome news for me as I actually want to mess with a more recent chip from this company.

Regards and stay safe!
